services:
  db:
    image: postgres
    container_name: dev_db
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: ${db_name}
    ports:
      - '${extern_db}:${db_port}'

  app:
    env_file:
      - .env
    container_name: dev_app
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - '${app_port}:${app_port}'
